title: Portfolio d'Arnaud Goetz
description: Portfolio professionnel - Développeur Full Stack | Parcours, expériences et projets
theme: minima

# Information personnelle
author:
  name: Arnaud Goetz
  email: arnaud.goetz@example.com

# Liens de navigation
header_pages:
  - index.md
  - parcours.md
  - experiences.md
  - projets.md
  - contact.md

# SEO et réseaux sociaux
lang: fr-FR
timezone: Europe/Paris

# GitHub configuration
github_username: ArnaudGoetz
linkedin_username: arnaudgoetz

# Configuration Jekyll
markdown: kramdown
permalink: pretty

# Exclude from processing
exclude:
  - README.md
  - .gitignore
  - assets/images/README.md
  - assets/documents/README.md
