# Configuration Jekyll
lang: fr-FR
title: "Portfolio – Arnaud Goetz"
description: "Portfolio technique : projets, expériences et compétences (rendu, génération procédurale, simulation, IA)"
# Thème demandé
theme: minimal
# Options générales
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
exclude:
  - README_LOCAL.md
# Navigation (liens directs)
# Pour un thème plus avancé, migrer vers just-the-docs plus tard.