# Configuration Jekyll
lang: fr-FR
title: "Portfolio – Arnaud Goetz"
description: "Portfolio technique : projets, expériences et compétences (rendu, génération procédurale, simulation, IA)"
# Thème demandé
theme: jekyll-theme-minimal
# Options générales
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
exclude:
  - README_LOCAL.md

# Navigation
nav:
  - title: "Accueil"
    url: /
  - title: "Parcours scolaire"
    url: /parcours
  - title: "Expériences professionnelles"
    url: /experiences
  - title: "Projets"
    url: /projets